# myinfo test
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3IiwiaWF0IjoxNTIzMzI3OTM0LCJleHAiOjE1MjM5MzI3MzR9.4SwEJFlWsBQV7YWqxq2wmbeJDghdyWQ4B7RW2GNvS1Dv6rywWMnZBoHhnmzpvnCyq6Ab-NPHYj6W22p_RIrehg

###