# myinfo test
GET http://localhost:8080/api/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3IiwiaWF0IjoxNTIzMTY1ODA3LCJleHAiOjE1MjM3NzA2MDd9.w381VNBZHZ2gxtR9L7OkrfnPcZOzDqiOow8XeLZctNDI_2SKUEdL7kBz0TVv4I_1wzQO0E1foar4XMLKxtoUHA

###