# signup test
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
	"username": "김민재",
	"email": "minjae@gmail.com",
	"password": "123456789",
	"userorwebtoonist": false
}

###